modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Milk%20All%20The%20Mobs"
logoFile="icon.png"

[[mods]]
modId="milkallthemobs"
version="3.1"
displayName="Milk All The Mobs"
displayURL="https://curseforge.com/minecraft/mc-mods/milk-all-the-mobs"
authors="Rick South"
description='''Allows sheep, llamas, pigs, donkeys, horses and mules to produce a bucket of milk.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.milkallthemobs]]
    modId="collective"
    mandatory=true
    versionRange="[7.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.milkallthemobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"